# NUMPY

In [1]:
!pip install numpy

In [4]:
import numpy as np
a = [1,2,3]
A = np.array(a)
print(A)
print(type(A))

[1 2 3]
<class 'numpy.ndarray'>


In [9]:
a = [[1,2,3],[4,5,6]]
A = np.array(a)
print(A)

[[1 2 3]
 [4 5 6]]


In [8]:
A[0][2]

3

In [20]:
A1 = np.array([[1,2,3],[4,5,6],[2,4,5]])
A2 = np.array([[7,8,9],[3,6,9],[4,5,7]])

In [15]:
A2.shape   #Order or matrix

(2, 3)

In [13]:
A2.size   #No of elements or size of matrix

6

In [17]:
print("Shape ",A2.shape)
print("Size ",A2.size)

Shape  (2, 3)
Size  6


In [18]:
A1 * A2

array([[ 7, 16, 27],
       [12, 30, 54]])

In [21]:
np.dot(A1,A2)     #Matrix Multiplication

array([[ 25,  35,  48],
       [ 67,  92, 123],
       [ 46,  65,  89]])

In [25]:
A1.tolist()    #Convert Array in to List

[[1, 2, 3], [4, 5, 6], [2, 4, 5]]

In [26]:
np.matrix(A1)

matrix([[1, 2, 3],
        [4, 5, 6],
        [2, 4, 5]])

In [27]:
np.array(A1)

array([[1, 2, 3],
       [4, 5, 6],
       [2, 4, 5]])

In [36]:
A2.reshape((1,9))

array([[7, 8, 9, 3, 6, 9, 4, 5, 7]])

In [37]:
A2.reshape((9,1))

array([[7],
       [8],
       [9],
       [3],
       [6],
       [9],
       [4],
       [5],
       [7]])

In [38]:
A2.reshape(1,9)

array([[7, 8, 9, 3, 6, 9, 4, 5, 7]])

In [39]:
A1.flatten()     #shows single array 

array([1, 2, 3, 4, 5, 6, 2, 4, 5])

In [43]:
print(A1.reshape(1,9))
print(A1.reshape(9,1))

[[1 2 3 4 5 6 2 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [2]
 [4]
 [5]]


# QUESTION HW

In [45]:
#Matrix 3*3 



In [56]:
##Only Get Int Value from List

a = [1,2,'a',5,'b','d',6]
b = [x for x in a if type(x) is int]
b

[1, 2, 5, 6]

In [70]:
#OR

b = [x for x in a if type(x) == int]
b

[1, 2, 5, 6]

In [68]:
a = [1,2,'a',5,'b','d',6]

for x in a:
    if type(x) == int:
        print(x)

1
2
5
6


In [72]:
l = range(20)
l

range(0, 20)

In [83]:
b = [x for x in l if x%2==0]
b

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [90]:
l = range(20)
l1 = []
for x in l:
    if x%2 == 0:
        l1.append("Even")
    else:
        l1.append("Odd")
    print(x, l1[x])

0 Even
1 Odd
2 Even
3 Odd
4 Even
5 Odd
6 Even
7 Odd
8 Even
9 Odd
10 Even
11 Odd
12 Even
13 Odd
14 Even
15 Odd
16 Even
17 Odd
18 Even
19 Odd


In [109]:
l = range(20)
l1 = []
for x in l:
    if x%2 == 0:
        l1.append(f"{x} -> Even")
    else:
        l1.append(f"{x} -> Odd")
print(l1)

['0 -> Even', '1 -> Odd', '2 -> Even', '3 -> Odd', '4 -> Even', '5 -> Odd', '6 -> Even', '7 -> Odd', '8 -> Even', '9 -> Odd', '10 -> Even', '11 -> Odd', '12 -> Even', '13 -> Odd', '14 -> Even', '15 -> Odd', '16 -> Even', '17 -> Odd', '18 -> Even', '19 -> Odd']


In [106]:
l = range(20)

l = [f"{x} --> Even" if x%2 == 0 else  f"{x} --> Odd" for x in l ]
l

['0 --> Even',
 '1 --> Odd',
 '2 --> Even',
 '3 --> Odd',
 '4 --> Even',
 '5 --> Odd',
 '6 --> Even',
 '7 --> Odd',
 '8 --> Even',
 '9 --> Odd',
 '10 --> Even',
 '11 --> Odd',
 '12 --> Even',
 '13 --> Odd',
 '14 --> Even',
 '15 --> Odd',
 '16 --> Even',
 '17 --> Odd',
 '18 --> Even',
 '19 --> Odd']

In [118]:
l2 = [1,2,'a','b',4,'c',6]
str(l2)

"[1, 2, 'a', 'b', 4, 'c', 6]"

In [124]:
file = open("l1.txt", "w")
file.write(str(l2))
file.close()

In [126]:
file = open("l1.txt","r")
file.read()

"[1, 2, 'a', 'b', 4, 'c', 6]"

In [127]:
file.close()